### ISSUE TITLE
Assign custom Textures/Sprites

### ISSUE THREAD

**Issue by NeatWolf** [Thundernerd/Unity3D-IconManager#2]
It's not an issue, but more a question, I hope it's the right place for this

To assign custom textures do I have to simply make the 

`private static void SetIcon( GameObject gObj, Texture2D texture ) {`

public?

Will the asset/gameobject keep that value? 
I have a setter/getter for that that also works in the editor (I've got Icons for interactions and I want the Gizmo Icon of the gameobject to reflect that).

Do I need to mark the whole gameobject to Dirty to keep the change?

**Comment by Thundernerd** [comment]
It would indeed be possible to just make that one public. I personally would not do it that way though.
I've pushed a new commit (b2fee8c) that adds an extra function to set a custom icon.
The reason I'm separating it is so that whenever a change is required the visible functions don't get their name changed. Only the underlying code changes.

You are, of course, free to choose the method you prefer.

As for the editor changes, I am not sure if you have to mark the object as dirty. If you want the change of icon to be save-able then I would indeed mark it as dirty. I believe that way the scene would also be marked dirty and when someone would change scenes you'll get a save prompt.

**Comment by NeatWolf** [comment]
Thanks for the update! 
You're perfectly right about that. I was just doing that the quick'n'dirty way :)

I'm going to check if everything works right now (Unity 5.4.2f2)

**Comment by NeatWolf** [comment]
Looks like it's already marking the scene as dirty when I use the extension, doesn't seem to be needed any other SetDirty call.

Thanks for the script, it's working like a charm! This should have been native!

**Comment by Thundernerd** [comment]
Oh really. It might be because it's using the same method that is being called whenever you change the icon through the inspector.

I'll close this thread but if you have any questions or issues feel free to open another one!

P.S. It's kinda native, just not for public use. But thanks for the compliment :)
